
version: '3'
services:

    fl-server:
        build: services/fl-server
        container_name: fl-server
        ports:
        - "5000:8080"
        environment:
            GRAPHQL_INTERFACE_URL: "http://gql-interface:7999/"
            SERVER_INTERNAL_HOST: "0.0.0.0"
            SERVER_INTERNAL_PORT: "8080"
            ROUNDS: "100"
        volumes:
        - ./experiments/mock-experiment/bases:/src/bases
        - ./experiments/synthea-breast-cancer/winter2022/Federated/experiment/:/src/experiment
    
    db-katsu:
        image: postgres:latest
        container_name: db-katsu
        environment:
            POSTGRES_DB: "${KATSU_POSTGRES_DB:-metadata}"
            POSTGRES_USER: "${KATSU_POSTGRES_USER:-admin}"
            POSTGRES_PASSWORD: "${KATSU_POSTGRES_PASSWORD:-admin}"
        ports:
        - "5001:5432"
        volumes:
        - db-katsu-data:/var/lib/postgresql/data

    katsu:
        build:
            context: services/katsu
            args:
                - venv_python=3.7
                - alpine_version=3.13
        container_name: katsu
        volumes:
        - ./services/katsu_entrypoint.sh:/app/katsu_entrypoint.sh
        - ../federated-learning/ingestion-scripts/internal:/app/chord_metadata_service/ingestion-scripts
        entrypoint: ["/app/katsu_entrypoint.sh"]
        ports:
        - "5002:8000"
        depends_on:
        - db-katsu
        environment:
            POSTGRES_HOST: "db-katsu"
            POSTGRES_PORT: 5432
            POSTGRES_DATABASE: "${KATSU_POSTGRES_DB:-metadata}"
            POSTGRES_USER: "${KATSU_POSTGRES_USER:-admin}"
            POSTGRES_PASSWORD: "${KATSU_POSTGRES_PASSWORD:-admin}"

    gql-interface:
        build: services/gql-interface
        container_name: gql-interface
        ports:
        - "5003:7999"
        environment:
            GRAPHQL_CANDIG_SERVER: "http://candig-dev:4000"
            GRAPHQL_KATSU_API: "http://katsu:8000/api"

    fl-client-1:
        build: services/fl-client
        container_name: fl-client-1
        depends_on:
        - fl-server
        environment:
            FLOWER_SERVER_URL: "fl-server:8080"
            GRAPHQL_INTERFACE_URL: "http://gql-interface:7999/"
            FLOWER_CLIENT_NUMBER: "1"
        volumes:
        - ./experiments/mock-experiment/bases:/src/bases
        - ./experiments/synthea-breast-cancer/winter2022/Federated/experiment/:/src/experiment

    fl-client-2:
        build: services/fl-client
        container_name: fl-client-2
        depends_on:
        - fl-server
        environment:
            FLOWER_SERVER_URL: "fl-server:8080"
            GRAPHQL_INTERFACE_URL: "http://gql-interface:7999/"
            FLOWER_CLIENT_NUMBER: "2"
        volumes:
        - ./experiments/mock-experiment/bases:/src/bases
        - ./experiments/synthea-breast-cancer/winter2022/Federated/experiment/:/src/experiment

volumes:
    db-katsu-data:
    