
version: '3'
services:

    fl-server:
        build: services/fl-server
        container_name: fl-server
        ports:
        - "5000:8080"
        environment:
            GRAPHQL_INTERFACE_URL: "http://gql-interface:7999/graphql"
    
    db-katsu:
        image: postgres:latest
        container_name: db-katsu
        environment:
            POSTGRES_DB: "${KATSU_POSTGRES_DB:-metadata}"
            POSTGRES_USER: "${KATSU_POSTGRES_USER:-admin}"
            POSTGRES_PASSWORD: "${KATSU_POSTGRES_PASSWORD:-admin}"
        ports:
        - "5001:5432"
        volumes:
        - katsu-db-data:/var/lib/postgresql/data

    katsu:
        image: ghcr.io/candig/candig-katsu:latest
        container_name: katsu
        volumes:
        - ./services/katsu_entrypoint.sh:/app/katsu_entrypoint.sh
        - ../federated-learning/ingestion_scripts/internal:/app/chord_metadata_service/ingestion_scripts
        entrypoint: ["/app/katsu_entrypoint.sh"]
        ports:
        - "5002:8000"
        depends_on:
        - db-katsu
        environment:
            POSTGRES_HOST: "
            "
            POSTGRES_PORT: 5432
            POSTGRES_DATABASE: "${KATSU_POSTGRES_DB:-metadata}"
            POSTGRES_USER: "${KATSU_POSTGRES_USER:-admin}"
            POSTGRES_PASSWORD: "${KATSU_POSTGRES_PASSWORD:-admin}"

    gql-interface:
        build: services/gql-interface
        container_name: gql-interface
        ports:
        - "5003:7999"
        environment:
            CANDIG_SERVER: "http://candig-dev:4000"
            KATSU_API: "http://katsu:8000/api"

    fl-client-0:
        build: services/fl-client
        container_name: fl-client-0
        depends_on:
        - fl-server
        environment:
            FLOWER_SERVER_URL: "fl-server:8080"
            GRAPHQL_INTERFACE_URL: "http://gql-interface:7999/graphql"

    fl-client-1:
        build: services/fl-client
        container_name: fl-client-1
        depends_on:
        - fl-server
        environment:
            FLOWER_SERVER_URL: "fl-server:8080"
            GRAPHQL_INTERFACE_URL: "http://gql-interface:7999/graphql"
        
volumes:
    
    katsu-db-data:
        