version: "3.7"

services:
  db-katsu:
    image: postgres:latest
    container_name: db-katsu
    environment:
      POSTGRES_DB: ${KATSU_POSTGRES_DB}
      POSTGRES_USER: ${KATSU_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KATSU_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - katsu-db-data:/var/lib/postgresql/data
  katsu:
    image: katsu
    container_name: katsu
    volumes:
      - ./services/katsu/katsu_entrypoint.sh:/app/katsu_entrypoint.sh
      - ./ingestion_scripts:/app/chord_metadata_service/ingestion_scripts
      - ./mohccn-data/mCode_ingest_scripts.json:/app/chord_metadata_service/scripts/mCode_ingest_scripts.json
      - ./synthea-1:/app/chord_metadata_service/synthea-1
    entrypoint: ["/app/katsu_entrypoint.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - db-katsu
    environment:
      POSTGRES_HOST: "db-katsu"
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: ${KATSU_POSTGRES_DB}
      POSTGRES_USER: ${KATSU_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KATSU_POSTGRES_PASSWORD}
      CANDIG_OPA_URL: http://opa:8181
    
volumes:
  katsu-db-data:
